import type { Metadata } from "next";
import { Hind_Siliguri } from "next/font/google";
import "./globals.css";
import Navber from "@/component/navber/Navber";
import Footer from "@/component/Footer";
import { ToastContainer } from "react-toastify";

const hind_siliguri = Hind_Siliguri({
  variable: "--font-hind_siliguri",
  subsets: ["latin", "bengali"],
  weight: ["400", "500", "600", "700"],
});



export const metadata: Metadata = {
  title: "বাজার দর",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="bn"
      className={`${hind_siliguri.variable} h-full antialiased`}
      data-theme="light"
    >
      <body className="min-h-full flex flex-col">
        <Navber />
        <main>{children}</main>
        <Footer />
        <ToastContainer />
      </body>
    </html>
  );
}
